services:
    phpmyadmin:
        image: docker.io/library/phpmyadmin:latest
        hostname: ${WARDEN_ENV_NAME}-phpmyadmin
        domainname: phpmyadmin.${WARDEN_ENV_NAME}.test
        environment:
          - PMA_HOSTS=${WARDEN_ENV_NAME}-db-1
          - PMA_USER=magento
          - PMA_PASSWORD=magento
          - PMA_ABSOLUTE_URI=https://phpmyadmin.${TRAEFIK_DOMAIN}
        labels:
          traefik.enable: "true"
          traefik.http.routers.(${WARDEN_ENV_NAME})-phpmyadmin.rule: Host(`phpmyadmin.${TRAEFIK_DOMAIN}`)
          traefik.http.routers.${WARDEN_ENV_NAME}-phpmyadmin.tls: "true"

